spring:
  application:
    name: chatter
  datasource:
    url: ${URL}
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default_schema: chatter
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  error:
    include-message: always